-- Add all Jeffco school district locations
-- Run with: psql $DATABASE_URL -f sql/add_schools.sql

INSERT INTO locations ("locationName", "isActive") VALUES 
-- Elementary Schools
('Adams Elementary School', TRUE),
('Bear Creek K-8 School', TRUE),
('Belmar School of Integrated Arts', TRUE),
('Bergen Elementary School', TRUE),
('Blue Heron Elementary School', TRUE),
('Bradford K-8 School', TRUE),
('Columbine Hills Elementary School', TRUE),
('Coronado Elementary School', TRUE),
('Deane Elementary School', TRUE),
('Dennison Elementary School', TRUE),
('Devinny Elementary School', TRUE),
('Dutch Creek Elementary School', TRUE),
('Edgewater Elementary School', TRUE),
('Eiber Elementary School', TRUE),
('Elk Creek Elementary School', TRUE),
('Fairmount Elementary School', TRUE),
('Fletcher Miller School', TRUE),
('Foothills Elementary School', TRUE),
('Foster Dual Language PK-8 School', TRUE),
('Free Horizon Montessori School', TRUE),
('Fremont Elementary School', TRUE),
('Governor''s Ranch Elementary School', TRUE),
('Green Gables Elementary School', TRUE),
('Hackberry Hill Elementary School', TRUE),
('Hutchinson Elementary School', TRUE),
('Jeffco Remote Learning Program', TRUE),
('Jefferson County Open School', TRUE),
('Kendallvue Elementary School', TRUE),
('Kendrick Lakes Elementary School', TRUE),
('Kyffin Elementary School', TRUE),
('Lasley Elementary School', TRUE),
('Lawrence Elementary School', TRUE),
('Leawood Elementary School', TRUE),
('Little Elementary School', TRUE),
('Lukas Elementary School', TRUE),
('Lumberg Elementary School', TRUE),
('Maple Grove Elementary School', TRUE),
('Marshdale Elementary School', TRUE),
('Meiklejohn Elementary', TRUE),
('Mitchell Elementary School', TRUE),
('Mortensen Elementary School', TRUE),
('Mount Carbon Elementary School', TRUE),
('Normandy Elementary School', TRUE),
('Parmalee Elementary School', TRUE),
('Patterson International School', TRUE),
('Peak Expeditionary School at Pennington', TRUE),
('Powderhorn Elementary School', TRUE),
('Prospect Valley Elementary School', TRUE),
('Ralston Elementary School', TRUE),
('Red Rocks Elementary School', TRUE),
('Rooney Ranch Elementary School', TRUE),
('Rose Stein International Elementary School', TRUE),
('Ryan Elementary School', TRUE),
('Secrest Elementary School', TRUE),
('Semper Elementary School', TRUE),
('Shaffer Elementary School', TRUE),
('Shelton Elementary School', TRUE),
('Sierra Elementary School', TRUE),
('Slater Elementary School', TRUE),
('Sobesky Academy', TRUE),
('South Lakewood Elementary School', TRUE),
('Stevens Elementary School', TRUE),
('Stober Elementary School', TRUE),
('Stony Creek Elementary School', TRUE),
('Stott Elementary School', TRUE),
('Swanson Elementary School', TRUE),
('Three Creeks K-8 School', TRUE),
('Ute Meadows Elementary School', TRUE),
('Van Arsdale Elementary School', TRUE),
('Vanderhoof Elementary School', TRUE),
('Warder Elementary School', TRUE),
('Weber Elementary School', TRUE),
('Welchester Elementary School', TRUE),
('West Jefferson Elementary School', TRUE),
('West Woods Elementary School', TRUE),
('Westgate Elementary School', TRUE),
('Westridge Elementary School', TRUE),
('Wilmot Elementary School', TRUE),
-- Middle Schools
('Bell Middle School', TRUE),
('Carmody Middle School', TRUE),
('Connections Learning Center', TRUE),
('Creighton Middle School', TRUE),
('Deer Creek Middle School', TRUE),
('D''Evelyn Junior/Senior High School', TRUE),
('Drake Middle School', TRUE),
('Dunstan Middle School', TRUE),
('Evergreen Middle School', TRUE),
('Everitt Middle School', TRUE),
('Falcon Bluffs Middle School', TRUE),
('Jeffco Virtual Academy', TRUE),
('Ken Caryl Middle School', TRUE),
('Mandalay Middle School', TRUE),
('Mount View Youth Service Center', TRUE),
('North Arvada Middle School', TRUE),
('Oberon Middle School', TRUE),
('Outdoor Lab', TRUE),
('Pomona Junior/Senior High School', TRUE),
('Summit Ridge Middle School', TRUE),
('The Manning School of Academics & Arts', TRUE),
('Wayne Carle Middle School', TRUE),
('West Jefferson Middle School', TRUE),
-- High Schools
('Alameda International Junior/Senior High School', TRUE),
('Arvada High School', TRUE),
('Arvada West High School', TRUE),
('Bear Creek High School', TRUE),
('Brady Exploration High School', TRUE),
('Chatfield High School', TRUE),
('Columbine High School', TRUE),
('Conifer High School', TRUE),
('Dakota Ridge High School', TRUE),
('Evergreen High School', TRUE),
('Golden High School', TRUE),
('Green Mountain High School', TRUE),
('Jeffco Transition Services School', TRUE),
('Jefferson Junior/Senior High School', TRUE),
('Lakewood High School', TRUE),
('Long View High School', TRUE),
('McLain Community High School', TRUE),
('Ralston Valley High School', TRUE),
('Standley Lake High School', TRUE),
('Warren Tech', TRUE),
('Wheat Ridge High School', TRUE)
ON CONFLICT DO NOTHING;
